'use client';
import { useEffect, useMemo, useState } from 'react';
import { STYLES } from '../lib/config';
import { DECK_FORMULAS, CHARACTER_MODES, CHARACTER_STYLES, COPY_STYLES, SLIDE_TYPES, DANI, REFERENCE_STYLES } from '../lib/creative-system';

async function api(url, options={}){
  const r=await fetch(url,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})}});
  const ct=r.headers.get('content-type')||'';
  if(!r.ok){ let m=`Request failed (${r.status})`; try{const j=ct.includes('json')?await r.json():null;m=j?.error||m;}catch{} throw new Error(m); }
  return ct.includes('json')?r.json():r;
}
const blankProduct={name:'',brand:'',description:'',audience:'',approved_claims:'',prohibited_claims:'',source_url:'',product_id:'',category:'',selected_image_urls:[]};
const REFERENCE_PREVIEWS={style1_cartoon:'/reference-styles/style1-cartoon.jpg',style2_animated_education:'/reference-styles/style2-animated.jpg',style3_social_dialogue:'/reference-styles/style3-dialogue.jpg',style3_realistic_editorial:'/reference-styles/style3b-realistic.jpg',style4_clean_animated:'/reference-styles/style4-clean-animated.jpg',style5_realistic_cover:'/reference-styles/style5-realistic-cover.jpg',style6_fashion_two_slide:'/reference-styles/style6-fashion.jpg',style7_problem_solution:'/reference-styles/style7-problem-solution.jpg',style8_chat_story:'/reference-styles/style8-chat.jpg'};

export default function Home(){
  const [tab,setTab]=useState('products'); const [products,setProducts]=useState([]); const [campaigns,setCampaigns]=useState([]); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(null);
  const [shopUrl,setShopUrl]=useState(''); const [region,setRegion]=useState('US'); const [scraped,setScraped]=useState(null); const [productDraft,setProductDraft]=useState(blankProduct); const [selectedImages,setSelectedImages]=useState([]);
  const [builderProductId,setBuilderProductId]=useState(''); const [referenceStyleId,setReferenceStyleId]=useState('style1_cartoon'); const [style,setStyle]=useState('Mixed Illustrated + UGC'); const [aspect,setAspect]=useState('3:4'); const [slideCount,setSlideCount]=useState(8); const [deckFormula,setDeckFormula]=useState('auto'); const [characterMode,setCharacterMode]=useState('reference'); const [character,setCharacter]=useState(''); const [creativeDirection,setCreativeDirection]=useState(''); const [concepts,setConcepts]=useState([]); const [conceptIndex,setConceptIndex]=useState(0); const [plan,setPlan]=useState(null);
  const [genCampaignId,setGenCampaignId]=useState(''); const [exportCampaignId,setExportCampaignId]=useState(''); const [health,setHealth]=useState(null);

  const load=async()=>{ try{ const [p,c]=await Promise.all([api('/api/products'),api('/api/campaigns')]); setProducts(p.products||[]); setCampaigns(c.campaigns||[]); if(!builderProductId&&p.products?.[0])setBuilderProductId(p.products[0].id); if(!genCampaignId&&c.campaigns?.[0])setGenCampaignId(c.campaigns[0].id); if(!exportCampaignId&&c.campaigns?.[0])setExportCampaignId(c.campaigns[0].id); }catch(e){setMessage({type:'error',text:e.message});} };
  useEffect(()=>{load();},[]);
  const selectedBuilderProduct=useMemo(()=>products.find(p=>p.id===builderProductId),[products,builderProductId]);
  const genCampaign=useMemo(()=>campaigns.find(c=>c.id===genCampaignId),[campaigns,genCampaignId]);
  const exportCampaign=useMemo(()=>campaigns.find(c=>c.id===exportCampaignId),[campaigns,exportCampaignId]);
  const selectedConcept=concepts[conceptIndex];
  const selectedReferenceStyle=REFERENCE_STYLES.find(x=>x.id===referenceStyleId)||REFERENCE_STYLES[0];

  function flash(text,type='success'){setMessage({text,type}); if(type!=='error')setTimeout(()=>setMessage(null),4500)}
  async function scrape(){ setBusy('scrape'); setMessage(null); try{ const x=await api('/api/socialvault',{method:'POST',body:JSON.stringify({url:shopUrl,region})}); setScraped(x.product); setProductDraft({...blankProduct,name:x.product.name||'',brand:x.product.brand||'',description:x.product.description||'',source_url:x.product.source_url||shopUrl,product_id:x.product.product_id||'',category:x.product.category||''}); setSelectedImages([]); flash(`Found ${x.product.name}`); }catch(e){flash(e.message,'error')} finally{setBusy('')} }
  function toggleImage(url){setSelectedImages(v=>v.includes(url)?v.filter(x=>x!==url):[...v,url]);}
  async function saveProduct(){ if(!productDraft.name.trim())return flash('Product name is required.','error'); setBusy('saveProduct'); try{ const x=await api('/api/products',{method:'POST',body:JSON.stringify({...productDraft,selected_image_urls:selectedImages})}); await load(); setScraped(null);setSelectedImages([]);setProductDraft(blankProduct);setShopUrl('');setBuilderProductId(x.product.id);flash('Product saved to library.'); }catch(e){flash(e.message,'error')}finally{setBusy('')} }
  async function conceptsRun(){ if(!selectedBuilderProduct)return flash('Save/select a product first.','error'); setBusy('concepts');setPlan(null);try{const x=await api('/api/ai',{method:'POST',body:JSON.stringify({action:'concepts',product:selectedBuilderProduct,creativeDirection,deckFormulaId:deckFormula,characterMode,referenceStyleId})});setConcepts(x.concepts||[]);setConceptIndex(0);flash('5 campaign concepts ready.');}catch(e){flash(e.message,'error')}finally{setBusy('')} }
  async function planRun(){ if(!selectedConcept)return flash('Generate and choose a concept first.','error');setBusy('plan');try{const x=await api('/api/ai',{method:'POST',body:JSON.stringify({action:'plan',product:selectedBuilderProduct,concept:selectedConcept,deckFormulaId:selectedConcept.deck_formula_id||deckFormula,slideCount:Number(slideCount),style,characterMode,characterDescription:character,creativeDirection,referenceStyleId})});setPlan(x.plan);flash('Slide plan ready — edit it before generating images.');}catch(e){flash(e.message,'error')}finally{setBusy('')} }
  function editPlanSlide(i,key,value){setPlan(p=>({...p,slides:p.slides.map((s,n)=>n===i?{...s,[key]:value}:s)}));}
  async function saveCampaign(){ if(!plan)return;setBusy('saveCampaign');try{const body={name:plan.name||selectedConcept.title,product_id_ref:selectedBuilderProduct.id,product_name:selectedBuilderProduct.name,style,aspect_ratio:aspect,character_mode:characterMode,character_description:character,creative_direction:creativeDirection,reference_style_id:referenceStyleId,concept:selectedConcept,deck_formula_id:plan.deck_formula_id||selectedConcept.deck_formula_id||deckFormula,slides:plan.slides,caption:'',slide_assets:{}};const x=await api('/api/campaigns',{method:'POST',body:JSON.stringify(body)});await load();setGenCampaignId(x.campaign.id);setExportCampaignId(x.campaign.id);setTab('generate');flash('Campaign saved. Generate slides when ready.');}catch(e){flash(e.message,'error')}finally{setBusy('')} }
  function mutateCampaign(local,key,value){setCampaigns(cs=>cs.map(c=>c.id===local.id?{...c,[key]:value}:c));}
  function mutateSlide(campaignId,index,key,value){setCampaigns(cs=>cs.map(c=>c.id!==campaignId?c:{...c,slides:c.slides.map(s=>Number(s.slide_index)===Number(index)?{...s,[key]:value}:s)}));}
  async function saveCampaignEdits(campaign){setBusy(`save-${campaign.id}`);try{const x=await api('/api/campaigns',{method:'PUT',body:JSON.stringify(campaign)});setCampaigns(cs=>cs.map(c=>c.id===x.campaign.id?x.campaign:c));flash('Changes saved.');}catch(e){flash(e.message,'error')}finally{setBusy('')}}
  async function generateSlide(index){if(!genCampaign)return;setBusy(`gen-${index}`);try{await saveCampaignQuiet(genCampaign);const x=await api('/api/generate-slide',{method:'POST',body:JSON.stringify({campaign_id:genCampaign.id,slide_index:index})});setCampaigns(cs=>cs.map(c=>c.id===x.campaign.id?x.campaign:c));flash(`Slide ${index} generated.`);}catch(e){flash(e.message,'error')}finally{setBusy('')}}
  async function saveCampaignQuiet(campaign){const x=await api('/api/campaigns',{method:'PUT',body:JSON.stringify(campaign)});setCampaigns(cs=>cs.map(c=>c.id===x.campaign.id?x.campaign:c));return x.campaign;}
  async function renderOnly(index){if(!genCampaign)return;setBusy(`render-${index}`);try{await saveCampaignQuiet(genCampaign);const x=await api('/api/render-slide',{method:'POST',body:JSON.stringify({campaign_id:genCampaign.id,slide_index:index})});setCampaigns(cs=>cs.map(c=>c.id===x.campaign.id?x.campaign:c));flash(`Slide ${index} regenerated with the updated text in GPT Image 2.`);}catch(e){flash(e.message,'error')}finally{setBusy('')}}
  async function generateAll(){
    if(!genCampaign)return; setBusy('generateAll');
    try{
      let current=await saveCampaignQuiet(genCampaign);
      for(const s of current.slides){
        if(current.slide_assets?.[s.slide_index])continue;
        const x=await api('/api/generate-slide',{method:'POST',body:JSON.stringify({campaign_id:current.id,slide_index:s.slide_index})});
        current=x.campaign; setCampaigns(cs=>cs.map(c=>c.id===current.id?current:c));
      }
      flash('All missing slides generated.');
    }catch(e){flash(e.message,'error')}finally{setBusy('')}
  }

  async function checkSetup(){setBusy('health');try{const x=await api('/api/health');setHealth(x);if(x.ok)flash('Setup check passed: OpenAI + Blob are reachable.');else flash(x.errors?.join('\n')||'Setup check failed.','error');}catch(e){flash(e.message,'error')}finally{setBusy('')}}
  async function uploadReplacement(index,file){if(!file||!genCampaign)return;setBusy(`upload-${index}`);try{await saveCampaignQuiet(genCampaign);const f=new FormData();f.append('campaign_id',genCampaign.id);f.append('slide_index',String(index));f.append('file',file);const x=await api('/api/upload-image',{method:'POST',body:f});setCampaigns(cs=>cs.map(c=>c.id===x.campaign.id?x.campaign:c));flash(`Replacement image saved for slide ${index}.`);}catch(e){flash(e.message,'error')}finally{setBusy('')}}
  async function captionRun(){if(!exportCampaign)return;setBusy('caption');try{const product=products.find(p=>p.id===exportCampaign.product_id_ref);const x=await api('/api/ai',{method:'POST',body:JSON.stringify({action:'caption',product,campaign:exportCampaign})});const updated={...exportCampaign,caption:x.caption};await saveCampaignQuiet(updated);setCampaigns(cs=>cs.map(c=>c.id===updated.id?updated:c));flash('Caption generated.');}catch(e){flash(e.message,'error')}finally{setBusy('')}}
  async function downloadZip(){if(!exportCampaign)return;setBusy('zip');try{await saveCampaignQuiet(exportCampaign);const r=await api('/api/export',{method:'POST',body:JSON.stringify({campaign_id:exportCampaign.id})});const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(exportCampaign.name||'campaign').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.zip`;a.click();URL.revokeObjectURL(a.href);}catch(e){flash(e.message,'error')}finally{setBusy('')}}

  return <main className="shell">
    <div className="topbar"><div className="brand"><h1>✦ Carousel Factory</h1><div className="muted">Vercel Edition · SocialVault → original TikTok slide skill → editable story → image generation → exact text → export</div></div><span className="badge">Phase 1 · Skill Engine V5</span></div>
    <div className="tabs">{[['products','1 · Products'],['builder','2 · Campaign Builder'],['generate','3 · Generate & Review'],['export','4 · Export']].map(([id,label])=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {message&&<div className={`notice ${message.type||''}`}>{message.text}</div>}

    {tab==='products'&&<section className="grid" style={{gap:18}}>
      <div className="panel"><h2 className="section-title">Pull product from TikTok Shop</h2><p className="section-sub">Paste the product link. SocialVault pulls official listing details and photos; you choose exactly which photos get saved.</p>
        <div className="grid g4"><div className="field" style={{gridColumn:'span 2'}}><label>TikTok Shop URL</label><input value={shopUrl} onChange={e=>setShopUrl(e.target.value)} placeholder="https://www.tiktok.com/view/product/..."/></div><div className="field"><label>Region</label><select value={region} onChange={e=>setRegion(e.target.value)}>{['US','GB','CA','AU','FR','DE'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>&nbsp;</label><button className="btn primary" disabled={!shopUrl||busy==='scrape'} onClick={scrape}>{busy==='scrape'?'Pulling…':'Pull product'}</button></div></div>
        {scraped&&<><div className="divider"/><div className="grid g2"><div className="field"><label>Product name</label><input value={productDraft.name} onChange={e=>setProductDraft({...productDraft,name:e.target.value})}/></div><div className="field"><label>Brand</label><input value={productDraft.brand} onChange={e=>setProductDraft({...productDraft,brand:e.target.value})}/></div><div className="field"><label>Audience</label><input value={productDraft.audience} onChange={e=>setProductDraft({...productDraft,audience:e.target.value})} placeholder="Who is this for?"/></div><div className="field"><label>Category</label><input value={productDraft.category} onChange={e=>setProductDraft({...productDraft,category:e.target.value})}/></div></div>
          <div className="field" style={{marginTop:12}}><label>Product details</label><textarea rows="7" value={productDraft.description} onChange={e=>setProductDraft({...productDraft,description:e.target.value})}/></div>
          <div className="grid g2" style={{marginTop:12}}><div className="field"><label>Approved / checkable claims</label><textarea value={productDraft.approved_claims} onChange={e=>setProductDraft({...productDraft,approved_claims:e.target.value})} placeholder="Optional: claims the campaign may use"/></div><div className="field"><label>Do not claim</label><textarea value={productDraft.prohibited_claims} onChange={e=>setProductDraft({...productDraft,prohibited_claims:e.target.value})} placeholder="Optional: claims/phrases to avoid"/></div></div>
          <h3>Choose product reference photos <span className="muted small">({selectedImages.length} selected)</span></h3><div className="thumbs">{(scraped.images||[]).map((url,i)=><div key={url} className={`thumb ${selectedImages.includes(url)?'selected':''}`} onClick={()=>toggleImage(url)}><img src={url} alt={`Product ${i+1}`}/>{selectedImages.includes(url)&&<span className="check">✓</span>}</div>)}</div>
          <div className="row" style={{marginTop:16}}><button className="btn primary" disabled={busy==='saveProduct'} onClick={saveProduct}>{busy==='saveProduct'?'Saving…':'Save selected product'}</button><span className="muted small">Price and stock are intentionally not imported.</span></div></>}
      </div>
      <div className="panel"><h2 className="section-title">Product Library</h2><p className="section-sub">Saved products are available to every campaign.</p><div className="products">{products.length?products.map(p=><div className="card" key={p.id}><div className="row between"><strong>{p.name}</strong><span className="badge">{p.image_urls?.length||0} refs</span></div><div className="muted small" style={{marginTop:5}}>{p.brand||'No brand'}{p.category?` · ${p.category}`:''}</div>{p.image_urls?.[0]&&<img src={p.image_urls[0]} alt="" style={{width:'100%',aspectRatio:'1/1',objectFit:'contain',background:'#fff',borderRadius:12,marginTop:12}}/>}</div>):<div className="muted">No saved products yet.</div>}</div></div>
    </section>}

    {tab==='builder'&&<section className="grid" style={{gap:18}}>
      <div className="panel"><h2 className="section-title">Campaign Setup</h2><p className="section-sub">Choose one of your real reference styles first. That preset controls the deck flow, copy rhythm, text treatment and image composition before the story is written.</p>
        <div className="grid g4">
          <div className="field"><label>Product</label><select value={builderProductId} onChange={e=>{setBuilderProductId(e.target.value);setConcepts([]);setPlan(null)}}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
          <div className="field"><label>Reference style</label><select value={referenceStyleId} onChange={e=>{const id=e.target.value;setReferenceStyleId(id);const preset=REFERENCE_STYLES.find(x=>x.id===id);if(preset?.defaultSlides)setSlideCount(preset.defaultSlides);setConcepts([]);setPlan(null)}}>{REFERENCE_STYLES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
          <div className="field"><label>Deck formula</label><select value={deckFormula} onChange={e=>{setDeckFormula(e.target.value);setConcepts([]);setPlan(null)}}>{DECK_FORMULAS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
          <div className="field"><label>Character</label><select value={characterMode} onChange={e=>setCharacterMode(e.target.value)}>{CHARACTER_MODES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
        </div>
        <div className="notice" style={{marginTop:12}}><div className="row" style={{alignItems:'flex-start',gap:16}}>{REFERENCE_PREVIEWS[referenceStyleId]&&<img src={REFERENCE_PREVIEWS[referenceStyleId]} alt="Selected style reference" style={{width:150,height:190,objectFit:'cover',borderRadius:12,background:'#fff'}}/>}<div><strong>{selectedReferenceStyle?.name}</strong><div style={{marginTop:6}}>{selectedReferenceStyle?.description}</div><div className="muted small" style={{marginTop:8}}>Default flow: {selectedReferenceStyle?.flow?.join(' → ')}</div></div></div></div>
        <div className="grid g4" style={{marginTop:12}}>
          <div className="field"><label>Aspect ratio</label><select value={aspect} onChange={e=>setAspect(e.target.value)}>{['3:4','9:16','4:5'].map(x=><option key={x}>{x}</option>)}</select></div>
          <div className="field"><label>Slides</label><select value={slideCount} onChange={e=>setSlideCount(Number(e.target.value))}>{[2,3,4,5,6,7,8,9,10].map(x=><option key={x}>{x}</option>)}</select></div>
          <div className="field"><label>Image finish</label><select value={style} onChange={e=>setStyle(e.target.value)}>{Object.keys(STYLES).map(x=><option key={x}>{x}</option>)}</select></div>
          <div className="field"><label>Creative direction (optional)</label><textarea value={creativeDirection} onChange={e=>setCreativeDirection(e.target.value)} placeholder="Example: relationship-based, gym-focused, women 35+, more emotional, etc."/></div>
        </div>
        {characterMode==='reference'&&<div className="notice" style={{marginTop:12}}><strong>Reference character mode is active.</strong> The selected style decides whether the deck uses a clean cartoon creator, an original yellow adult-animation-inspired cast, a realistic UGC creator, or no recurring person.</div>}{characterMode==='dani'&&<div className="notice" style={{marginTop:12}}><strong>Dani is active.</strong> Character slides use the original skill identity, expression IDs E1–E6 and pose IDs P1–P6. Product reveal/CTA slides switch to real product UGC.</div>}
        {characterMode==='custom'&&<div className="field" style={{marginTop:12}}><label>Custom recurring character</label><textarea value={character} onChange={e=>setCharacter(e.target.value)} placeholder="Describe identity, hair, clothing/accessories and any locked traits. Keep this character consistent across character slides."/></div>}
        <div className="row" style={{marginTop:14}}><button className="btn primary" disabled={!selectedBuilderProduct||busy==='concepts'} onClick={conceptsRun}>{busy==='concepts'?'Thinking…':concepts.length?'Regenerate 5 concepts':'Generate 5 concepts'}</button><span className="muted small">Reference style = primary production preset. Deck formula and angle only shape the story inside that preset.</span></div>
      </div>

      {concepts.length>0&&<div className="panel"><h2 className="section-title">Choose a campaign angle</h2><div className="grid g3">{concepts.map((c,i)=><div key={i} className={`card concept ${i===conceptIndex?'selected':''}`} onClick={()=>setConceptIndex(i)}><div className="row between"><strong>{c.title}</strong><span className="badge">{c.total_score}/25</span></div><p>{c.hook}</p><div className="row" style={{marginBottom:8}}><span className="badge">{DECK_FORMULAS.find(x=>x.id===c.deck_formula_id)?.name||c.deck_formula_id}</span><span className="badge">{c.angle_mechanism_id?.replaceAll('_',' ')}</span></div><div className="muted small">{c.story_promise}</div>{c.product_fact&&<div className="fact"><strong>Grounded in:</strong> {c.product_fact}</div>}<div style={{marginTop:10}}>{Object.entries(c.scores||{}).map(([k,v])=><span className="score" key={k}>{k.replaceAll('_',' ')} {v}/5</span>)}</div></div>)}</div><div className="row" style={{marginTop:16}}><button className="btn primary" disabled={busy==='plan'} onClick={planRun}>{busy==='plan'?'Building story…':'Build slide plan'}</button><span className="muted small">{selectedReferenceStyle?.name} · {DECK_FORMULAS.find(x=>x.id===selectedConcept?.deck_formula_id)?.name||selectedConcept?.deck_formula_id}</span></div></div>}

      {plan&&<div className="panel"><h2 className="section-title">Edit the story before generating</h2><p className="section-sub">The selected reference preset has already assigned the intended slide types and copy treatments. Edit the wording/scene only when needed before image generation.</p><div className="field"><label>Campaign name</label><input value={plan.name} onChange={e=>setPlan({...plan,name:e.target.value})}/></div><div className="slides" style={{marginTop:14}}>{plan.slides.map((s,i)=><div className="card" key={i}><div className="row between"><strong>Slide {s.slide_index}</strong><div className="row"><span className="badge">{s.role}</span><span className="badge">{s.slide_type_id} · {SLIDE_TYPES[s.slide_type_id]?.name||'Slide'}</span></div></div>
        <div className="grid g2" style={{marginTop:10}}><div className="field"><label>Slide type</label><select value={s.slide_type_id} onChange={e=>editPlanSlide(i,'slide_type_id',e.target.value)}>{Object.entries(SLIDE_TYPES).map(([id,x])=><option key={id} value={id}>{id} — {x.name}</option>)}</select></div><div className="field"><label>Copy style</label><select value={s.text_style} onChange={e=>editPlanSlide(i,'text_style',e.target.value)}>{Object.entries(COPY_STYLES).map(([id,x])=><option key={id} value={id}>{x.name}</option>)}</select></div></div>
        <div className="field"><label>Exact on-image text</label><textarea value={s.text} onChange={e=>editPlanSlide(i,'text',e.target.value)}/></div>{s.text_style==='type2'&&<div className="field"><label>Hook emphasis phrase</label><input value={s.emphasis_text||''} onChange={e=>editPlanSlide(i,'emphasis_text',e.target.value)} placeholder="Short phrase from the hook that should be oversized burgundy editorial text"/></div>}
        <div className="field"><label>Visual</label><textarea value={s.visual} onChange={e=>editPlanSlide(i,'visual',e.target.value)}/></div>
        <div className="grid g4"><div className="field"><label>Character style</label><select value={s.character_style||'none'} onChange={e=>editPlanSlide(i,'character_style',e.target.value)}>{CHARACTER_STYLES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>Expression</label><select value={s.expression_id||'none'} onChange={e=>editPlanSlide(i,'expression_id',e.target.value)}><option value="none">None</option>{Object.entries(DANI.expressions).map(([id,x])=><option key={id} value={id}>{id} — {x}</option>)}</select></div><div className="field"><label>Pose</label><select value={s.pose_id||'none'} onChange={e=>editPlanSlide(i,'pose_id',e.target.value)}><option value="none">None</option>{Object.entries(DANI.poses).map(([id,x])=><option key={id} value={id}>{id} — {x}</option>)}</select></div><div className="field"><label>Text position</label><select value={s.text_position} onChange={e=>editPlanSlide(i,'text_position',e.target.value)}>{['top','middle','bottom'].map(x=><option key={x}>{x}</option>)}</select></div></div>
        <div className="grid g2"><div className="field"><label>Font size</label><input type="number" min="40" max="110" value={s.font_size} onChange={e=>editPlanSlide(i,'font_size',Number(e.target.value))}/></div><div className="field"><label>Stickers / arrows note</label><input value={s.stickers||''} onChange={e=>editPlanSlide(i,'stickers',e.target.value)}/></div></div>
        <label className="row small" style={{marginTop:10}}><input style={{width:'auto'}} type="checkbox" checked={s.product_visible} onChange={e=>editPlanSlide(i,'product_visible',e.target.checked)}/> Product visible</label></div>)}</div><div className="row" style={{marginTop:16}}><button className="btn primary" disabled={busy==='saveCampaign'} onClick={saveCampaign}>{busy==='saveCampaign'?'Saving…':'Approve & save campaign'}</button></div></div>}
    </section>}

    {tab==='generate'&&<section className="panel"><div className="row between"><div><h2 className="section-title">Generate & Review</h2><p className="section-sub">The chosen reference preset stays attached to the campaign so regenerations keep the same deck DNA. Regenerate one image without touching the rest.</p></div><div className="row"><select style={{minWidth:280}} value={genCampaignId} onChange={e=>setGenCampaignId(e.target.value)}><option value="">Select campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.product_name}</option>)}</select><button className="btn" disabled={busy==='health'} onClick={checkSetup}>{busy==='health'?'Checking…':'Check setup'}</button><button className="btn primary" disabled={!genCampaign||busy==='generateAll'} onClick={generateAll}>{busy==='generateAll'?'Generating slides…':'Generate missing'}</button><button className="btn" disabled={!genCampaign||busy.startsWith('save-')} onClick={()=>saveCampaignEdits(genCampaign)}>Save edits</button></div></div>{health&&<div className={`notice ${health.ok?'':'error'}`} style={{marginBottom:14}}>{health.ok?'✓ Setup OK — Blob write + OpenAI image model check passed.':`Setup problem: ${(health.errors||[]).join(' | ')}`}</div>}
      {!genCampaign?<div className="muted">Create a campaign in Campaign Builder first.</div>:<><div className="notice" style={{marginBottom:14}}><strong>{REFERENCE_STYLES.find(x=>x.id===genCampaign.reference_style_id)?.name||'Reference style'}</strong> · {DECK_FORMULAS.find(x=>x.id===genCampaign.deck_formula_id)?.name||genCampaign.deck_formula_id} · {genCampaign.character_mode==='reference'?'Reference style character':genCampaign.character_mode==='dani'?'Dani character system':genCampaign.character_mode==='custom'?'Custom recurring character':'No recurring character'} · {genCampaign.aspect_ratio}</div><div className="slides">{genCampaign.slides.map(s=>{const asset=genCampaign.slide_assets?.[s.slide_index];return <div className="card slide-card" key={s.slide_index}>{asset?.final_url?<img src={`${asset.final_url}${asset.final_url.includes('?')?'&':'?'}v=${encodeURIComponent(asset.rendered_at||asset.generated_at||'')}`} alt={`Slide ${s.slide_index}`}/>:<div className="empty">Slide {s.slide_index} not generated</div>}<div className="row between" style={{marginTop:10}}><strong>Slide {s.slide_index}</strong><div className="row"><span className="badge">{s.role}</span><span className="badge">{s.slide_type_id} · {SLIDE_TYPES[s.slide_type_id]?.name||'Slide'}</span></div></div>
        <div className="grid g2" style={{marginTop:8}}><div className="field"><label>Slide type</label><select value={s.slide_type_id} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'slide_type_id',e.target.value)}>{Object.entries(SLIDE_TYPES).map(([id,x])=><option key={id} value={id}>{id} — {x.name}</option>)}</select></div><div className="field"><label>Copy style</label><select value={s.text_style||'type4'} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'text_style',e.target.value)}>{Object.entries(COPY_STYLES).map(([id,x])=><option key={id} value={id}>{x.name}</option>)}</select></div></div>
        <div className="field"><label>Exact text</label><textarea value={s.text} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'text',e.target.value)}/></div>{s.text_style==='type2'&&<div className="field"><label>Emphasis phrase</label><input value={s.emphasis_text||''} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'emphasis_text',e.target.value)}/></div>}<div className="field"><label>Visual prompt</label><textarea value={s.visual} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'visual',e.target.value)}/></div>
        <div className="grid g4"><div className="field"><label>Character style</label><select value={s.character_style||'none'} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'character_style',e.target.value)}>{CHARACTER_STYLES.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>Expression</label><select value={s.expression_id||'none'} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'expression_id',e.target.value)}><option value="none">None</option>{Object.entries(DANI.expressions).map(([id,x])=><option key={id} value={id}>{id} — {x}</option>)}</select></div><div className="field"><label>Pose</label><select value={s.pose_id||'none'} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'pose_id',e.target.value)}><option value="none">None</option>{Object.entries(DANI.poses).map(([id,x])=><option key={id} value={id}>{id} — {x}</option>)}</select></div><div className="field"><label>Text position</label><select value={s.text_position} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'text_position',e.target.value)}>{['top','middle','bottom'].map(x=><option key={x}>{x}</option>)}</select></div></div>
        <div className="field"><label>Font size</label><input type="number" value={s.font_size} min="40" max="110" onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'font_size',Number(e.target.value))}/></div><label className="row small" style={{margin:'9px 0'}}><input style={{width:'auto'}} type="checkbox" checked={s.product_visible} onChange={e=>mutateSlide(genCampaign.id,s.slide_index,'product_visible',e.target.checked)}/> Product visible</label><div className="row"><button className="btn primary" disabled={busy===`gen-${s.slide_index}`} onClick={()=>generateSlide(s.slide_index)}>{busy===`gen-${s.slide_index}`?'Generating…':asset?'Regenerate image':'Generate image'}</button><button className="btn" disabled={!asset||busy===`render-${s.slide_index}`} onClick={()=>renderOnly(s.slide_index)}>Regenerate with text</button><label className="btn" style={{cursor:'pointer'}}>Upload final slide<input className="hidden" type="file" accept="image/*" onChange={e=>uploadReplacement(s.slide_index,e.target.files?.[0])}/></label>{asset?.final_url&&<a className="btn" href={asset.final_url} target="_blank" rel="noreferrer">Open</a>}</div></div>})}</div></>}
    </section>}

    {tab==='export'&&<section className="panel"><div className="row between"><div><h2 className="section-title">Export Campaign</h2><p className="section-sub">Generate/edit the caption, then download every completed slide plus campaign data in one ZIP.</p></div><select style={{minWidth:320}} value={exportCampaignId} onChange={e=>setExportCampaignId(e.target.value)}><option value="">Select campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.product_name}</option>)}</select></div>{exportCampaign&&<><div className="field"><label>Caption</label><textarea rows="6" value={exportCampaign.caption||''} onChange={e=>mutateCampaign(exportCampaign,'caption',e.target.value)}/></div><div className="row" style={{marginTop:12}}><button className="btn" disabled={busy==='caption'} onClick={captionRun}>{busy==='caption'?'Writing…':'Generate caption'}</button><button className="btn" onClick={()=>saveCampaignEdits(exportCampaign)}>Save caption</button><button className="btn primary" disabled={busy==='zip'} onClick={downloadZip}>{busy==='zip'?'Building ZIP…':'Download campaign ZIP'}</button></div><div className="notice" style={{marginTop:16}}>{Object.keys(exportCampaign.slide_assets||{}).length} of {exportCampaign.slides.length} slides have generated assets.</div></>}</section>}
  </main>
}
